### ISSUE TITLE
Support remote configuration definition

### ISSUE THREAD

**Issue by robzienert** [spinnaker/dcd-spec#2]
Some users want the ability to retrieve pipeline configurations from a remote source, similar to how we resolve pipeline templates from remote sources. This remote source should be capable of supporting different formats, such as JSON, Java Properties, etc.

**Comment by yusha2016** [comment]
while a support to pipeline TestA and TesB, the TestB is configuration a auto Trigger job depends TestA, And the TestB pipeline is config with pipeline templates from remote source, while i work TestB pipeline with single , it can be worked ok, but while i work TestA first, the TestB work by trigger, it can not work ok error by can not find any stages
