### ISSUE TITLE
How to enable `pipelineTemplates` into `settings.js` of Deck?

### ISSUE THREAD

**Issue by tchemineau** [spinnaker/dcd-spec#8]
Hi,

I am currently interesting by the Pipeline Templates feature of Spinnaker, for enforcing Infrastructure As Code in my deployments. So, I would like to enable this feature into my current Spinnaker deployment (deployed into Kubernetes).

I am reading this document: https://github.com/spinnaker/dcd-spec/blob/master/ALPHA-GETTING-STARTED.md

As I know how to configure `orca-local.yml` via my hal settings, I don't know how to configure Deck, by adding `pipelineTemplates` parameter into the `settings.js` (which is part of a "secret" in my Kubernetes deployment).

How do you do that?

Thanks

Thomas.

**Comment by robzienert** [comment]
@danielpeach

**Comment by danielpeach** [comment]
Hi,

I'm working on support for this in Halyard right now. It should be done soon (today or tomorrow).

If you really want this right now, I would follow the 'Custom Profiles' guide for Halyard: https://www.spinnaker.io/reference/halyard/custom/#custom-profiles.

You'll need to copy a full `settings.js` with all the values you want into `~/.hal/$DEPLOYMENT/service-settings/settings.js`.

**Comment by danielpeach** [comment]
I should have mentioned that the Halyard support will be in soon, but will those changes not have an effect on your Spinnaker deployment until we release Spinnaker 1.2.

**Comment by ssakhuja57** [comment]
Any update on the enabling of pipelines being supported in halyard?

**Comment by davidxia** [comment]
@danielbwatson Are there any updates on this?

**Comment by davidxia** [comment]
I see `--pipeline-templates` [here](https://www.spinnaker.io/reference/halyard/commands/#hal-config-features-edit). Does this mean this issue can be closed?

**Comment by agnnn** [comment]
@robzienert `hal config features edit --pipeline-templates true`  This command should enable pipeline template feature in spinnaker , But it dosent work for me!  Should i do anything more than setting this config ??

**Comment by KeisukeYamashita** [comment]
I am on the same problem after deploying the spinnaker by GCPs Cloud launcher.
How can I set it to `true`?

**Comment by rodriguezsergio** [comment]
Don't mean to resurrect an ancient issue, but you don't need to copy the full `settings.js` file to `~/.hal/$DEPLOYMENT` directory. You just need the following:

```
# ~/.hal/default/profiles/settings-local.js 
window.spinnakerSettings.feature.pipelineTemplates = true
```
